### ISSUE TITLE
SMPL mesh rendering from new_joint skeleton

### ISSUE THREAD

**Issue by kimjaeyoonn** [EricGuo5513/HumanML3D#100]
I estimated the SMPL from video containing a person's static motion, and extracted the new_joint through your code.
Result of checking new_joint with animation.py. There seems to be no problem.

https://github.com/EricGuo5513/HumanML3D/assets/87240205/7efb68d1-3d42-4338-b036-3ac64e28fa77

However, when SMPL mesh rendering from new_joint, 
there are problems with neck bending and direction occur, as shown in the attached video.
Where did it go wrong?
![024246_gt](https://github.com/EricGuo5513/HumanML3D/assets/87240205/54fe0dfe-2638-429c-bb09-6d4b42930ba2)

@EricGuo5513 Please help..

**Comment by ForeverAurorak** [comment]
> I estimated the SMPL from video containing a person's static motion, and extracted the new_joint through your code. Result of checking new_joint with animation.py. There seems to be no problem.
> 
>  000000.mp4 
> However, when SMPL mesh rendering from new_joint, there are problems with neck bending and direction occur, as shown in the attached video. Where did it go wrong? ![024246_gt](https://private-user-images.githubusercontent.com/87240205/280609446-54fe0dfe-2638-429c-bb09-6d4b42930ba2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTkxNDUsIm5iZiI6MTcwOTc5ODg0NSwicGF0aCI6Ii84NzI0MDIwNS8yODA2MDk0NDYtNTRmZTBkZmUtMjYzOC00MjljLWJiMDktNmQ0YjQyOTMwYmEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA4MDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmQ3YzUwZTVkNmQ4YTQxOGQwZjFmZWE3NTVjYWUwMTU2YzVlMjc5YzAxYmFiMDM4ZjkzOTA3N2JmYWI3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO7XpiwK0pzmlJ5osNbQ00Lt4htdaiZvn9g8FzvRbLI) [ ![024246_gt](https://private-user-images.githubusercontent.com/87240205/280609446-54fe0dfe-2638-429c-bb09-6d4b42930ba2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTkxNDUsIm5iZiI6MTcwOTc5ODg0NSwicGF0aCI6Ii84NzI0MDIwNS8yODA2MDk0NDYtNTRmZTBkZmUtMjYzOC00MjljLWJiMDktNmQ0YjQyOTMwYmEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA4MDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmQ3YzUwZTVkNmQ4YTQxOGQwZjFmZWE3NTVjYWUwMTU2YzVlMjc5YzAxYmFiMDM4ZjkzOTA3N2JmYWI3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO7XpiwK0pzmlJ5osNbQ00Lt4htdaiZvn9g8FzvRbLI) ](https://private-user-images.githubusercontent.com/87240205/280609446-54fe0dfe-2638-429c-bb09-6d4b42930ba2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTkxNDUsIm5iZiI6MTcwOTc5ODg0NSwicGF0aCI6Ii84NzI0MDIwNS8yODA2MDk0NDYtNTRmZTBkZmUtMjYzOC00MjljLWJiMDktNmQ0YjQyOTMwYmEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA4MDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmQ3YzUwZTVkNmQ4YTQxOGQwZjFmZWE3NTVjYWUwMTU2YzVlMjc5YzAxYmFiMDM4ZjkzOTA3N2JmYWI3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO7XpiwK0pzmlJ5osNbQ00Lt4htdaiZvn9g8FzvRbLI) [ ](https://private-user-images.githubusercontent.com/87240205/280609446-54fe0dfe-2638-429c-bb09-6d4b42930ba2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTkxNDUsIm5iZiI6MTcwOTc5ODg0NSwicGF0aCI6Ii84NzI0MDIwNS8yODA2MDk0NDYtNTRmZTBkZmUtMjYzOC00MjljLWJiMDktNmQ0YjQyOTMwYmEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA4MDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmQ3YzUwZTVkNmQ4YTQxOGQwZjFmZWE3NTVjYWUwMTU2YzVlMjc5YzAxYmFiMDM4ZjkzOTA3N2JmYWI3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO7XpiwK0pzmlJ5osNbQ00Lt4htdaiZvn9g8FzvRbLI)
> 
> @EricGuo5513 Please help..

Hi, can you tell me how you rendered the following video using new_joint?

**Comment by Run542968** [comment]
Hi, how did you recover SMPL parameters from joints? Can you help me? orz @kimjaeyoonn
