### ISSUE TITLE
Error in raw_pose_processing.ipynb

### ISSUE THREAD

**Issue by mishrap9** [EricGuo5513/HumanML3D#101]
Hi @EricGuo5513,
I followed all the steps of raw_pose_processing.ipynb and I am facing this error which I am not able to get rid off.

`for i in tqdm(range(total_amount)):`
   ` #import pdb; pdb.set_trace()`
    source_path = index_file.loc[i]['source_path']
    new_name = index_file.loc[i]['new_name']
    data = np.load(source_path)
    start_frame = index_file.loc[i]['start_frame']
    end_frame = index_file.loc[i]['end_frame']
    if 'humanact12' not in source_path:
        if 'Eyes_Japan_Dataset' in source_path:
            data = data[3*fps:]
        if 'MPI_HDM05' in source_path:
            data = data[3*fps:]
        if 'TotalCapture' in source_path:
            data = data[1*fps:]
        if 'MPI_Limits' in source_path:
            data = data[1*fps:]
        if 'Transitions_mocap' in source_path:
            data = data[int(0.5*fps):]
        data = data[start_frame:end_frame]
        data[..., 0] *= -1
    
    data_m = swap_left_right(data)
#     save_path = pjoin(save_dir, )
    np.save(pjoin(save_dir, new_name), data)
    np.save(pjoin(save_dir, 'M'+new_name), data_m)`

I get this error:
![Screenshot from 2023-11-09 03-46-41](https://github.com/EricGuo5513/HumanML3D/assets/68013363/d32f50ee-408f-4b30-9182-87096a660f03)

It is not clear from any of the issues and also from the readme file how to proceed in this case. 

Looking forward to hearing from you.

**Comment by CGYZ515** [comment]
> Hi @EricGuo5513, I followed all the steps of raw_pose_processing.ipynb and I am facing this error which I am not able to get rid off.
> 
> `for i in tqdm(range(total_amount)):` ` #import pdb; pdb.set_trace()` source_path = index_file.loc[i]['source_path'] new_name = index_file.loc[i]['new_name'] data = np.load(source_path) start_frame = index_file.loc[i]['start_frame'] end_frame = index_file.loc[i]['end_frame'] if 'humanact12' not in source_path: if 'Eyes_Japan_Dataset' in source_path: data = data[3_fps:] if 'MPI_HDM05' in source_path: data = data[3_fps:] if 'TotalCapture' in source_path: data = data[1_fps:] if 'MPI_Limits' in source_path: data = data[1_fps:] if 'Transitions_mocap' in source_path: data = data[int(0.5*fps):] data = data[start_frame:end_frame] data[..., 0] *= -1
> 
> ```
> data_m = swap_left_right(data)
> ```
> 
> # save_path = pjoin(save_dir, )
> ```
> np.save(pjoin(save_dir, new_name), data)
> np.save(pjoin(save_dir, 'M'+new_name), data_m)`
> ```
> 
> I get this error: ![Screenshot from 2023-11-09 03-46-41](https://private-user-images.githubusercontent.com/68013363/281599580-d32f50ee-408f-4b30-9182-87096a660f03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDc0MTIsIm5iZiI6MTczMDgwNzExMiwicGF0aCI6Ii82ODAxMzM2My8yODE1OTk1ODAtZDMyZjUwZWUtNDA4Zi00YjMwLTkxODItODcwOTZhNjYwZjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDExNDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZDc4NTY4OTZlMWVjZTcyNTg5ZDE1ZWViMDc2ZmQ2ZjRlYTRjNTZlMTFkZjNmZGI2MGUyZDJhYTBiYzA4ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VerzZXx96nkXHKHTRixNrb7uUTIOr67nOID7Hc72AlA)
> 
> It is not clear from any of the issues and also from the readme file how to proceed in this case.
> 
> Looking forward to hearing from you.

Hello, I also encountered this problem, may I ask you have solved it?

**Comment by RebelAKL** [comment]
i encouter the same issue, any soln yet??

**Comment by Aphrody-Dy** [comment]
Hi, I encountered the same problem, is there any solution?

**Comment by Aphrody-Dy** [comment]
> Hi, I encountered the same problem, is there any solution?

Oh, I got it. Just create a folder named "joints" and the issue will be solved.
