### ISSUE TITLE
`No such file or directory: './pose_data/KIT/3/kick_high_left02_poses.npy'` by running `raw_pose_processing.ipynb` 

### ISSUE THREAD

**Issue by gitforziio** [EricGuo5513/HumanML3D#11]
Hi! Thank you for the wonderful dataset. 

I got some error by running `raw_pose_processing.ipynb`: `No such file or directory: './pose_data/KIT/3/kick_high_left02_poses.npy'`.
It seems that there were no `3` folder in the `KIT` dataset too.

```
---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

Input In [12], in <cell line: 1>()
      2 source_path = index_file.loc[i]['source_path']
      3 new_name = index_file.loc[i]['new_name']
----> 4 data = np.load(source_path)
      5 start_frame = index_file.loc[i]['start_frame']
      6 end_frame = index_file.loc[i]['end_frame']

File ~\anaconda3\envs\TM2T\lib\site-packages\numpy\lib\npyio.py:390, in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    388     own_fid = False
    389 else:
--> 390     fid = stack.enter_context(open(os_fspath(file), "rb"))
    391     own_fid = True
    393 # Code to distinguish from NumPy binary files and pickles.

FileNotFoundError: [Errno 2] No such file or directory: './pose_data/KIT/3/kick_high_left02_poses.npy'
```

**Comment by EricGuo5513** [comment]
Hi, have you ever downloaded the raw dataset from AMASS?

**Comment by JosephKKim** [comment]
Hello @gitforziio, did you managed to solve this issue? 
If you did, can you answer issue #25 ?

Thanks

**Comment by gitforziio** [comment]
Hello @JosephKKim and @EricGuo5513, I'm sorry for the delayed response. Recently, I was assigned to another project and had to relocate to another city without my previous computer, so it was difficult for me to continue working on this dataset.

Upon reviewing the documentation for this dataset, I noticed that it wasn't particularly clear. At the time, I was a complete novice in this field and was not familiar with AMASS, as mentioned by @EricGuo5513.

However, I have recently come across the corresponding paper and project website ( https://arxiv.org/abs/1904.03278 , https://amass.is.tue.mpg.de/ ).

I haven't had the chance to try running the code yet, but I hope this information is helpful for you @JosephKKim. Please let me know if you have made any progress. Regards.
