### ISSUE TITLE
motion_representation errors

### ISSUE THREAD

**Issue by CMY-CTO** [EricGuo5513/HumanML3D#120]
![image](https://github.com/EricGuo5513/HumanML3D/assets/58409065/64333441-24ef-4e55-826b-928d9070f9da)
Hello!
When I tried to process the `.ipynb` file `motion_representation`, it couldn't run successfully. I think there's some wrong occurred.
Reference the errors' screenshots attached.
Thanks in advance!

![image](https://github.com/EricGuo5513/HumanML3D/assets/58409065/c880dd37-e2dc-4020-9b55-c15323c9748e)

**Comment by CMY-CTO** [comment]
I guess those npy files, including 009707 and 11059, are not needed for motion_representation?
Maybe the original file does size 0 even though I don't think it's possible

**Comment by CMY-CTO** [comment]
<img width="584" alt="image" src="https://github.com/EricGuo5513/HumanML3D/assets/58409065/4d53ddfe-1df9-4924-9b07-299101e02f06">
I found some fantastic things after searching from the original `index.csv` file.
Only one frame in the 009707 and 11059?!
<img width="461" alt="image" src="https://github.com/EricGuo5513/HumanML3D/assets/58409065/5411b974-8dbc-432b-9a33-1807ffc7356d">

**Comment by SuperIRabbit** [comment]
Yeah I got similar errors:
```
Error processing 009707.npy:
cannot reshape array of size 0 into shape (0,newaxis)
Error processing M009707.npy:
cannot reshape array of size 0 into shape (0,newaxis)
Error processing 011059.npy:
cannot reshape array of size 0 into shape (0,newaxis)
Error processing M011059.npy:
cannot reshape array of size 0 into shape (0,newaxis)
```

**Comment by EricGuo5513** [comment]
Hi, there are a few motions only containing less than 1 poses. Just skip
them. Actually motions with less than 40 poses will be skipped in the
motion data loader (for training models) anyway.
