### ISSUE TITLE
Quick questions about mirroring script

### ISSUE THREAD

**Issue by purvaten** [EricGuo5513/HumanML3D#124]
Hi @EricGuo5513 , thank you for the great work and dataset release!

I am trying to use the processing script for a different dataset and had a quick question in [raw_pose_processing.ipynb](https://github.com/EricGuo5513/HumanML3D/blob/main/raw_pose_processing.ipynb). Specifically in Cell 13:
- Can you explain why the data is shifted for a few datasets? Does `fps` have the literal meaning here, or is something else happening?
- Why do you do `data[..., 0] *= -1`? And why is it not done for `humanact12`?
- Is there any reason you chose `20 fps` or was it an arbitrary choice? I understand that a lot of AMASS datasets are originally collected at 30, 60, or 120 fps, and I am just trying to understand the reason for bringing them all to 20.

For context, I am just trying to figure out a reasonable step for this part of the code for my dataset.

Thank you in advance.

**Comment by EricGuo5513** [comment]
Hello, hope the following answers your question:
1. For these datasets, they have static T-pose motions at the beginning or
the end. These are just cutting off the range of static motions (e.g.,
2s->2*fps)
2. I forgot the specific reason. It's trying to make the facing direction
Z+. HumanAct 12 has been processed.
3. The fps of HumanAct12 is 15 actually. Some datasets have fps of 40 or
100. 20 is a common fps that can be downsampled. On the other hand, high
fps will make the sequence too long to be generated at that time.

**Comment by purvaten** [comment]
This is very helpful. Thank you!
