### ISSUE TITLE
Critical Issue: Overlap of 3766 IDs between train_val.txt and test.txt

### ISSUE THREAD

**Issue by Morris-Lucifer** [EricGuo5513/HumanML3D#128]
### Description
While conducting a routine check on our dataset, I discovered that there are 3766 overlapping IDs between `train_val.txt` and `test.txt`. This overlap might affect the integrity of our training and testing processes, as the same IDs are not supposed to appear in both sets.

### Steps to Reproduce
1. Extract IDs from `train_val.txt` and `test.txt`.
2. Find the intersection of these two sets of IDs.
3. Count the number of overlapping IDs.

### Expected Behavior
`train_val.txt` and `test.txt` should have distinct sets of IDs with no overlap to ensure the separation of training/validation and testing data.

### Actual Behavior
There are 3766 IDs that appear in both `train_val.txt` and `test.txt`, indicating a significant overlap.

### Possible Solution
We need to investigate how these overlapping IDs were included in both files and ensure that the data splitting process segregates the IDs correctly without any overlaps.

**Comment by EricGuo5513** [comment]
Hi, thanks for pointint out this VERY CRITICAL issue. I have a quick check. You are absolutely correct, that there are huge amount of overlaping ids bettween `train_val.txt` and `test.txt`. I also checked the file `train.txt`, `test.txt` and `val.txt`, and find no overlaping. There must be errors while mergeing `train.txt` and `val.txt` files.

**Comment by Morris-Lucifer** [comment]
Thank you very much for the swift response and resolution of this issue!
