### ISSUE TITLE
get the part of speech of a word

### ISSUE THREAD

**Issue by zhuangzhuang000** [EricGuo5513/HumanML3D#13]
Dear author, 
Could you share the code you use to get the part of speech of a word?

**Comment by EricGuo5513** [comment]
Hi,

You can look into the text_process.py file.

Best,

Chuan

**Comment by Gelercatty** [comment]
hi there, i am working on my self built dataset, i only have the raw caption, i need process the raw caption to tokens, so i want that file too,or could you tell me how do you processed your raw text caption?

**Comment by lyk412** [comment]
> hi there, i am working on my self built dataset, i only have the raw caption, i need process the raw caption to tokens, so i want that file too,or could you tell me how do you processed your raw text caption?

I also want to build my own dataset. Have you found a way to handle raw text caption now?
