### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Frequency-Sensitive-Meat** [EricGuo5513/HumanML3D#14]
I am attempting to run this on Windows.

In the raw_pose_processing.ipynb script, I get this error. 

![image](https://user-images.githubusercontent.com/101849758/201496046-507e8622-a488-4608-8346-e8f1ba045095.png)

**Comment by EricGuo5513** [comment]
Hi, are sure you have downloaded the raw dataset from AMASS webpage?

**Comment by CuberFan** [comment]
<img width="479" alt="企业微信截图_9c2fb113-39a8-4921-8a87-0cd252e80710" src="https://user-images.githubusercontent.com/44254924/224263107-4423898e-c58f-4a8f-9dd1-46a7cca40d30.png">

**Comment by anyboby** [comment]
While the issue was closed, for completeness: 

This issue can occur when there is a non-folder inside "./amass_data", e.g. a license file. 
The above snippet fixes it anyhow.
