### ISSUE TITLE
Possible bug in `recover_root_from_rot` and solutions

### ISSUE THREAD

**Issue by LvXinTao** [EricGuo5513/HumanML3D#142]
Hi, I try to visualize the resulst of the original motion and recovered motion from `recover_from_ric`. However, the results seem quite different between them, especially in root trajectory. Here's the visualization:
The original motion after initially facing Z+:

https://github.com/user-attachments/assets/a4ff2f13-91e6-4841-b83a-2154d205fc64

The recovered motion:

https://github.com/user-attachments/assets/ae0f4bac-0d19-4fc3-b198-31f09d0c6dc7

You can see that the root trajectory differs a lot. After delving into your code, I finally found the reason. In [this line]( https://github.com/EricGuo5513/HumanML3D/blob/74f44681a6327cbc14fba6c3258884e69fe032b5/common/skeleton.py#L74), you represent the global rotation of root as rotation from forward direction to Z+, which is ok, as you mentioned in #35. And this is also why you do `qrot_np(r_rot,positions)` instead of the inverse of it in the following procedures. However, in the recovery function, you still do the `qrot(r_rot,positions)` , but the r_rot here represents **forward to Z+ instead of Z+ to forward**!  So the correct code should be 
```
def recover_root_rot_pos(data):
    rot_vel = data[..., 0]
    r_rot_ang = torch.zeros_like(rot_vel).to(data.device)
    '''Get Y-axis rotation from rotation velocity'''
    r_rot_ang[..., 1:] = rot_vel[..., :-1]
    r_rot_ang = torch.cumsum(r_rot_ang, dim=-1)

    r_rot_quat = torch.zeros(data.shape[:-1] + (4,)).to(data.device)
    r_rot_quat[..., 0] = torch.cos(r_rot_ang)
    r_rot_quat[..., 2] = torch.sin(r_rot_ang)

    r_pos = torch.zeros(data.shape[:-1] + (3,)).to(data.device)
    r_pos[..., 1:, [0, 2]] = data[..., :-1, 1:3]
    '''Add Y-axis rotation to root position'''
    r_pos = qrot(qinv(r_rot_quat), r_pos)     # MODIFICATION IN THIS LINE


    r_pos = torch.cumsum(r_pos, dim=-2)

    r_pos[..., 1] = data[..., 3]
    return r_rot_quat, r_pos
```
and 
```
def recover_from_ric(data, joints_num):
    r_rot_quat, r_pos = recover_root_rot_pos(data)
    positions = data[..., 4:(joints_num - 1) * 3 + 4]
    positions = positions.view(positions.shape[:-1] + (-1, 3)) 

    '''Add Y-axis rotation to local joints'''
    positions = qrot(qinv(r_rot_quat[..., None, :].expand(positions.shape[:-1] + (4,))), positions)  # MODIFICATION IN THIS LINE

    '''Add root XZ to joints'''
    positions[..., 0] += r_pos[..., 0:1]
    positions[..., 2] += r_pos[..., 2:3]

    '''Concate root and joints'''
    positions = torch.cat([r_pos.unsqueeze(-2), positions], dim=-2)

    return positions
```
After the correction, I visulaze it and the result seems finally right as below:

https://github.com/user-attachments/assets/6efa3f9b-ac2c-40d8-a0ae-3a58322e1a02

I hope you can clarify if this is right.

**Comment by EricGuo5513** [comment]
Hi,

Thanks for pointing this out.

Let me have a check before I can answer your question.

**Comment by EricGuo5513** [comment]
Hi, I checked the code in https://github.com/EricGuo5513/HumanML3D/blob/main/motion_representation.ipynb. It's exactly doing what you said here.
`
    r_pos = qrot(qinv(r_rot_quat), r_pos)`

` positions = qrot(qinv(r_rot_quat[..., None, :]).expand(positions.shape[:-1] + (4,)), positions)
`

Am I understanding your question correctly?

**Comment by LvXinTao** [comment]
Oh! I'm sorry for the mistake. It seems that the code I got has some problems : (  the code you post here is right in the repo. So soory for bothering!
