### ISSUE TITLE
cannot reshape array of size 0 into shape (0,newaxis)

### ISSUE THREAD

**Issue by yangzhao1230** [EricGuo5513/HumanML3D#15]
Hi Eric,

Thanks for your great work. When I run _motion_representation.ipynb_,  I meet the following errors.
![image](https://user-images.githubusercontent.com/52462696/201553637-587b9cd1-d796-401b-abfb-e085bde51ec2.png)
I wonder if it matters? And how to solve it.

**Comment by EricGuo5513** [comment]
Hi,

This should be fine.

**Comment by katsully** [comment]
I'm getting the same errors. The errors also stop the rest of the files from processing so it seems like an issue, no?

**Comment by qiqiApink** [comment]
I also got this issue. How can I fix this?

**Comment by EricGuo5513** [comment]
Just skip these lines by using try ... except.... There are only very a few
of them has this error.

qiqiApink ***@***.***> 于2023年3月7日周二 07:17写道：
