### ISSUE TITLE
Confused on Dataset

### ISSUE THREAD

**Issue by n12iki** [EricGuo5513/HumanML3D#17]
Hi,
I downloaded the KIT dataset and I am getting confused about how to understand it. So I am looking at the 00001.npy and these are the shapes I am getting.
new_joint_vecs
(47, 251)
new_joints
(47, 21, 3)

I am assuming that 47 is the number of frames. I am confused by what 251 is. The 21,3 is clearly the x,y,z joints. Thanks

**Comment by EricGuo5513** [comment]
Hi, the 251-dim vectors are motion features extracted using motion_representation.ipynb.
