### ISSUE TITLE
could not find   "/dataset/kit_mocap_dataset/desc_final.csv"

### ISSUE THREAD

**Issue by 24kbijin** [EricGuo5513/HumanML3D#19]
Dear Eric:
    As for the text coding, I am not very familiar with it. 
     **When I ran the text_process.py file, I was prompted that the contents of this folder of dataset were missing.**
    Could you tell me where I can download this folder?

    Looking forward to your reply!

**Comment by Mayao15** [comment]
How did you solve the problem? I am meeting the same problem.

**Comment by mkstmyk** [comment]
@bojin-nwafu I also got the same error. How did you find desc_final.csv? Thank you in advance.
