### ISSUE TITLE
About raw_offsets

### ISSUE THREAD

**Issue by hoyeYang** [EricGuo5513/HumanML3D#2]
Thanks for your great work! I wonder what the raw_offsets in paramUtil.py stands for?
https://github.com/EricGuo5513/HumanML3D/blob/e8417a6030844bc9f09767b6831a27b00330b1da/paramUtil.py#L32-L57
 And if I want to add another two joints (22 and 37) how to modify the raw_offsets and kinematic_chain? Could you give me some help?

**Comment by EricGuo5513** [comment]
This inverse/forward kinematics may need some background knowledge. I attached a [script](https://drive.google.com/file/d/1_PUbVETPf55p_ywulg4v76P5FRlNCyop/view?usp=sharing) which may help you understand this process. Note the script is using Lie Group/Algebra representation. While in our case, it's quaternion.

If you want to add other joints, you need to append these joints in existing kinematic chains. So these joints could be reached while inverse/forward kinematics along chains. These chains are the structure of the human body. For raw offset, We ususally make it roughly align with a pre-defined pose, which help animation in 3D software. But, as long as you keep its norm as 1, and keep it the same while inverse/forward kinematics, it should be fine. You could check whether you could reconstruct the positions by inverse and then forward kinematics. If you could, then you should be alright.

**Comment by hoyeYang** [comment]
Thanks a lot!
