### ISSUE TITLE
Question about the raw_pose_processing.ipynb

### ISSUE THREAD

**Issue by xiezhy6** [EricGuo5513/HumanML3D#20]
Hi,

 the following code is from `raw_pose_processing.ipynb`, and I am confused that why the first dimension of the `data` should be multiplied `-1` before being send to the function `swap_left_right`?

```
for i in tqdm(range(total_amount)):
    source_path = index_file.loc[i]['source_path']
    new_name = index_file.loc[i]['new_name']
    data = np.load(source_path)
    start_frame = index_file.loc[i]['start_frame']
    end_frame = index_file.loc[i]['end_frame']
    if 'humanact12' not in source_path:
        if 'Eyes_Japan_Dataset' in source_path:
            data = data[3*fps:]
        if 'MPI_HDM05' in source_path:
            data = data[3*fps:]
        if 'TotalCapture' in source_path:
            data = data[1*fps:]
        if 'MPI_Limits' in source_path:
            data = data[1*fps:]
        if 'Transitions_mocap' in source_path:
            data = data[int(0.5*fps):]
        data = data[start_frame:end_frame]
        data[..., 0] *= -1
    
    data_m = swap_left_right(data)
#     save_path = pjoin(save_dir, )
    np.save(pjoin(save_dir, new_name), data)
    np.save(pjoin(save_dir, 'M'+new_name), data_m)
```

**Comment by EricGuo5513** [comment]
Hi,

It’s kind of hard to explain. Swap left and right only exchange the index
of left body and right body. However, we still want to make the position of
left body on the right side. If you try to mirror one single case, you may
understand this.

Best,

Chuan

**Comment by EricGuo5513** [comment]
Oh I see, it’s not for mirroring, but for transforming coordinates so the
characters are facing z+ ( not precisely) direction. We have done this for
HumanAct12 already, so we only apply this for other datasets.
