### ISSUE TITLE
Are those errors are in the normal range?

### ISSUE THREAD

**Issue by qinghuannn** [EricGuo5513/HumanML3D#21]
Hi, thanks for your nice work! 
The errors are shown in the following images. I am not sure whether those errors are in the normal range? 
![image](https://user-images.githubusercontent.com/24269148/207824518-be775138-eed5-47e8-9fbf-4eaa6a917d03.png)
![image](https://user-images.githubusercontent.com/24269148/207827507-ee3b037c-8159-4189-951e-eeefccfe5fef.png)

**Comment by lingan1996** [comment]
I find these errors are caused by the matplotlib. After installing matplotlib (3.3.4), the difference between generated data and reference data is 0.

**Comment by EricGuo5513** [comment]
Hi thanks for letting me know! That is very helpful.

**Comment by EricGuo5513** [comment]
> Hi, thanks for your nice work! The errors are shown in the following images. I am not sure whether those errors are in the normal range? ![image](https://user-images.githubusercontent.com/24269148/207824518-be775138-eed5-47e8-9fbf-4eaa6a917d03.png) ![image](https://user-images.githubusercontent.com/24269148/207827507-ee3b037c-8159-4189-951e-eeefccfe5fef.png)

Also, this is actually very small error. Let's say. The vector is 263-dim, which means for each dim the error is as small as e-4.

**Comment by JosephKKim** [comment]
When ran motion_representation.ipynb the error was much larger than this
<img width="545" alt="image" src="https://user-images.githubusercontent.com/56065530/212797089-e194cedb-d2fe-4381-a2fd-8bc16383c67c.png">

But when I ran cal_mean_variance, the errors remained small is this okay?
<img width="502" alt="image" src="https://user-images.githubusercontent.com/56065530/212797179-13ff70c6-3090-493f-bb68-f0ecb6717c5d.png">

**Comment by EricGuo5513** [comment]
Hi, this should be okay. Considering there are thousands of element in the
reference data.

**Comment by JosephKKim** [comment]
Thanks, by the way I just resolved the previous issue I've been working on for a while thanks for the fast reply.

Joseph

**Comment by netanellavisdris** [comment]
Hi,
I've got these error too, and matplotlib==3.3.4
Is it OK? 

![image](https://user-images.githubusercontent.com/30286562/214314891-0515971c-79da-49fb-8435-26135b971f4d.png)
![image](https://user-images.githubusercontent.com/30286562/214314995-f0701855-03ef-4bde-a620-e7cf70f7a852.png)

Thanks!
   Netanell.

**Comment by EricGuo5513** [comment]
Hi, this should be totally fine.

**Comment by will-wang19** [comment]
> When ran motion_representation.ipynb the error was much larger than this <img alt="image" width="545" src="https://user-images.githubusercontent.com/56065530/212797089-e194cedb-d2fe-4381-a2fd-8bc16383c67c.png">
> 
> But when I ran cal_mean_variance, the errors remained small is this okay? <img alt="image" width="502" src="https://user-images.githubusercontent.com/56065530/212797179-13ff70c6-3090-493f-bb68-f0ecb6717c5d.png">
> 
> I am using matplotlib (3.3.4)

Hi, how do you reduce errors when you run motion_representation.ipynb?
