### ISSUE TITLE
About the data preprocessing

### ISSUE THREAD

**Issue by xuying156209** [EricGuo5513/HumanML3D#23]
Hi, thx for the nice work. The jupyter scripts are very helpful for learning the preprocessing pipeline.  However, I don't quite understand why converting the joints representation to position in raw_pose_processing and then normalizing the position in motion_representation by ik + fk process.  Is that ok to use the fixed shape to calculate the location of 'new_joints'?  Thx！

**Comment by EricGuo5513** [comment]
Hi, we use the ik+fk to retarget all the poses into the same skeleton. I guess you are asking about using the same SMPL shape to obtain the uniform-skeleton poses. My answer is yes. I think basically that is doing the same things. But not sure if that could generate the same results as us.
