### ISSUE TITLE
Question regarding the output from motion_representation.ipynb

### ISSUE THREAD

**Issue by zxwang96** [EricGuo5513/HumanML3D#24]
Hi,

I found the following output from the motion_representation.ipynb script. I wonder is this an issue or we can just ignore it?

![Screenshot from 2022-12-27 00-16-56](https://user-images.githubusercontent.com/28090369/209615081-7863a568-5adc-4913-87ba-5d61b2730ee2.png)

**Comment by EricGuo5513** [comment]
This is normal. You can ignore it.

**Comment by zxwang96** [comment]
Ok, thanks. Closing this issue.
