### ISSUE TITLE
About KIT dataset

### ISSUE THREAD

**Issue by JosephKKim** [EricGuo5513/HumanML3D#25]
Hello, @EricGuo5513 thanks for releasing this dataset!

While processing dataset with the given raw_pose_processing.ipynb file, I got an error that says, no file named ./pose_data/KIT/3/kick_high_left02_poses.npy, 
so I looked into the KIT dataset which I've downloaded from the AMASS webpage,
( I've downloaded SMPL-X N from the AMASS webpage, which gives me KIT.tar.bz2) 
the file extension was .npz instead of .npy. 

I tried to change its name to .npz but it gives the error message which says
KeyError: 'slice(0, 117, None) is not a file in the archive'

In this case, what would be the problem? 
thanks!

Joseph

**Comment by EricGuo5513** [comment]
Hi,

What is the shape of this array?

**Comment by JosephKKim** [comment]
It seems like after np.load .npz files, the variable named data is still a npz file.

**Comment by JosephKKim** [comment]
In addition, I just unrar dataset given in this repository (new_joint_vecs and new_joints)  but it gives error while running cal_mean_variance.ipynb

The error is as the screen capture below.
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/56065530/210339276-7c1f6b67-3db0-47aa-ba31-6a587d97d7d1.png">

**Comment by EricGuo5513** [comment]
Hello, sorry for the late reply. You need to download SMPL+H G on AMASS website, instead of SMPL-X N. Not sure if that triggers the error. 

The raw_pose_process script should be able to load with whatever data formate AMASS provides, as the SMPL part follows https://github.com/nghorbani/amass/tree/master/notebooks. In this case, the script should load npz data rather than npy data. We just save the data in npy format.

For cal_mean_variance script, HumanML3D dataset should have dimension of 263. Could you make sure that you have passed 22 to argument joints_num in mean_variance.

**Comment by JosephKKim** [comment]
No it's okay, I know that every researchers are living very busy life👍🏻

So let me wrap up this issue real quick. 

1. If I want to process from the raw AMASS dataset I should download SMPL + H G
2. If I don't want to start from the raw data, I should unzip the rar files you provided and unrar them -> get new_joint_vecs and use them to run rest of the .ipynb files
right?

But, when I tried to validate those files through running cal_mean_variance I'm getting error like the one below.
![image](https://user-images.githubusercontent.com/56065530/211442733-80cdb5e2-8cd2-4106-a708-400bea71c569.png)

What should I do?

**Comment by EricGuo5513** [comment]
Hi,

I got it. I think what you downloaded is KIT-ML dataset, it’s not or not
part of HumanML3D. It has different skeletons and number of joints. To
obtain HumanML3D, you have to download AMASS and run the scripts from
scratch, as we can not spread AMASS publicly.

Best,

Chuan

**Comment by EricGuo5513** [comment]
> No it's okay, I know that every researchers are living very busy life👍🏻
> 
> So let me wrap up this issue real quick.
> 
> 1. If I want to process from the raw AMASS dataset I should download SMPL + H G
> 2. If I don't want to start from the raw data, I should unzip the rar files you provided and unrar them -> get new_joint_vecs and use them to run rest of the .ipynb files
>    right?
> 
> But, when I tried to validate those files through running cal_mean_variance I'm getting error like the one below. ![image](https://user-images.githubusercontent.com/56065530/211442733-80cdb5e2-8cd2-4106-a708-400bea71c569.png)
> 
> What should I do?

Where did you get these new_joint_vecs

**Comment by JosephKKim** [comment]
Just by unrar new_joint_vecs.rar from your Google Drive.

**Comment by EricGuo5513** [comment]
> Just by unrar new_joint_vecs.rar from your Google Drive.

Could you send me the link? It seems the data you obtained is KIT-ML dataset, instead of HumanML3D.

**Comment by HuYicheng** [comment]
Hello, @EricGuo5513 . I just encounter the same problem. I have download KIT SMPL + H G. And I try to run this script raw_pose_processing.ipynb

Then failed with this warning

 FileNotFoundError: [Errno 2] No such file or directory: './pose_data/KIT/3/kick_high_left02_poses.npy'

In this directory, the file extention is npz rather than npy.

**Comment by JosephKKim** [comment]
Sorry for the late reply, 
So, since AMASS dataset is the collection of human motion capture dataset, I have downloaded all data from the official site, [AMASS](https://amass.is.tue.mpg.de/index.html).
After that, following the README from the repository I have downloaded KIT-ML dataset from [KIT-ML](https://drive.google.com/drive/folders/1MnixfyGfujSP-4t8w_2QvjtTVpEKr97t), and I think new_joint_vecs.rar and new_joints.rar are KIT-ML dataset(Am I right?).

So from the discussion before, what KIT-ML and HumanML3D is different dataset, and let's focus on the HumanML3D.
I think I followed all the instruction from the raw_pose_processing.ipynb, still getting the same error message @HuYicheng  is pointing out. I think users will need more specific and detailed instruction in order to get HumanML dataset correctly. I know that making README instructions is very time consuming work, but it would help more confused users like me. 

Thanks.

**Comment by HuYicheng** [comment]
Hi@JosephKKim. Have you resolved the problem and contructed HumanML3D dataset successfully after downloading the whole data from AMASS?

**Comment by JosephKKim** [comment]
@HuYicheng 
No, I'm still working on it and found something, while looking on the raw_pose_processing file, I think the problem is with the 3rd cell. 
printing the variable named dataset_names, which is a list. It gives an empty list. 

If this is the case I think we should fix the code. 
Tell me if you are getting the same result.

**Comment by JosephKKim** [comment]
Hi, @HuYicheng 
I found the solution for making .npy file, and also what was missing in the .ipynb instruction which caused the confusion in our communication between the author and users.

First, after reading the text part in the given notebook file, I found out that the authors is recommending to process 1 sub-dataset at the time (as you know that AMASS is consist of many sub-datasets which I refer to sub-dataset is something like KIT, SFU, MPI_Limits ... etc.).

So in the 4th line of the 4th cell, which is the code below, 
`       for root, dirs, files in os.walk('./amass_data'):
`
you have to add the sub-dataset to the path inside the os.walk. For example, for the KIT sub-dataset
` os.walk('./amass_data/KIT')
`

After that you can see that it is processing with the raw data which is in npz formats and converting it into npy formats.

Hope that it would help you and other users who might be confused about using this HumanML3D dataset.

DONE!

**Comment by JosephKKim** [comment]
You're welcome @HuYicheng, I always get help from github issues.
By the way, I think this work has to be done in sequential manner, which means after going through all the sub_dataset with the 4th cell, you can proceed to the next step which requires 000000.npy which is a new name for ./pose_data/KIT/3/kick_high_left02_poses.npy... 

Anyway, you'll get into another error message but since the main issue has been resolved I think we can figure it out or we can ask again to the author. 
Have a nice day.

**Comment by ntamotsu** [comment]
**(FYI)**

> Error looks like the one below.
FileNotFoundError: [Errno 2] No such file or directory: './joints/000000.npy'

→ https://github.com/EricGuo5513/HumanML3D/pull/61/files#diff-d3aa84b1613411a26692696ed0ffbe9419f4059ccb88378624855f9897355567R334

**Comment by CGYZ515** [comment]
``> You're welcome @HuYicheng, I always get help from github issues. By the way, I think this work has to be done in sequential manner, which means after going through all the sub_dataset with the 4th cell, you can proceed to the next step which requires 000000.npy which is a new name for ./pose_data/KIT/3/kick_high_left02_poses.npy...
> 
> Error looks like the one below.
> 
> > FileNotFoundError: [Errno 2] No such file or directory: './joints/000000.npy'
> 
> Anyway, you'll get into another error message but since the main issue has been resolved I think we can figure it out or we can ask again to the author. Have a nice day.

Hi，when I was running raw_pose_processing.ipynb, I encountered the FileNotFoundError you mentioned: [Errno 2] No such file or directory: './joints/000000.npy', can you provide some suggestions? Thank you！！
```
FileNotFoundError                         Traceback (most recent call last)
Cell In[63], line 23
     21     data_m = swap_left_right(data)
     22 #     save_path = pjoin(save_dir, )
---> 23     np.save(pjoin(save_dir, new_name), data)
     24     np.save(pjoin(save_dir, 'M'+new_name), data_m)

File <__array_function__ internals>:5, in save(*args, **kwargs)

File ~/miniconda3/envs/bevformer/lib/python3.8/site-packages/numpy/lib/npyio.py:524, in save(file, arr, allow_pickle, fix_imports)
    522     if not file.endswith('.npy'):
    523         file = file + '.npy'
--> 524     file_ctx = open(file, "wb")
    526 with file_ctx as fid:
    527     arr = np.asanyarray(arr)

FileNotFoundError: [Errno 2] No such file or directory: './joints/000000.npy'
```

**Comment by JiaqiJiang1206** [comment]
> ``> You're welcome @HuYicheng, I always get help from github issues. By the way, I think this work has to be done in sequential manner, which means after going through all the sub_dataset with the 4th cell, you can proceed to the next step which requires 000000.npy which is a new name for ./pose_data/KIT/3/kick_high_left02_poses.npy...
> 
> > Error looks like the one below.
> > > FileNotFoundError: [Errno 2] No such file or directory: './joints/000000.npy'
> > 
> > 
> > Anyway, you'll get into another error message but since the main issue has been resolved I think we can figure it out or we can ask again to the author. Have a nice day.
> 
> Hi，when I was running raw_pose_processing.ipynb, I encountered the FileNotFoundError you mentioned: [Errno 2] No such file or directory: './joints/000000.npy', can you provide some suggestions? Thank you！！
> 
> ```
> FileNotFoundError                         Traceback (most recent call last)
> Cell In[63], line 23
>      21     data_m = swap_left_right(data)
>      22 #     save_path = pjoin(save_dir, )
> ---> 23     np.save(pjoin(save_dir, new_name), data)
>      24     np.save(pjoin(save_dir, 'M'+new_name), data_m)
> 
> File <__array_function__ internals>:5, in save(*args, **kwargs)
> 
> File ~/miniconda3/envs/bevformer/lib/python3.8/site-packages/numpy/lib/npyio.py:524, in save(file, arr, allow_pickle, fix_imports)
>     522     if not file.endswith('.npy'):
>     523         file = file + '.npy'
> --> 524     file_ctx = open(file, "wb")
>     526 with file_ctx as fid:
>     527     arr = np.asanyarray(arr)
> 
> FileNotFoundError: [Errno 2] No such file or directory: './joints/000000.npy'
> ```

I resolved this issue by creating a new folder named `joints`. After doing this, this error no longer occurred. I'm not sure if this will work for your case, but it might be worth trying.
