### ISSUE TITLE
fail to check dataset, not generated dataset correctly

### ISSUE THREAD

**Issue by ChenFengYe** [EricGuo5513/HumanML3D#3]
Hi, this is quite confusing. After generating all dataset, the check part show the differernt with your provided samping.
Maybe this comes from the downloaded version of AMASS (mine might not be all from SMPLH+G).

./HumanML3D/motion_representation.ipynb
`abs(reference1 - reference1_1).sum()`
0.0031513844
`abs(reference2 - reference2_1).sum()`
0.01839152

./HumanML3D/cal_mean_variance.ipynb
`abs(mean-reference1).sum()`
0.010486759
`abs(std-reference2).sum()`
0.0014993595

**Comment by EricGuo5513** [comment]
Hi, this amount of deviation should be in normal range. This error is actually really small.

**Comment by ChenFengYe** [comment]
> Hi, this amount of deviation should be in normal range. This error is actually really small.

Thank you for the explanation. Nice work!

**Comment by MartinXM** [comment]
I encounter similar problem with @ChenFengYe. Although the difference in Mean and Std is relatively small, it causes a difference in all the metrics, including GT. Is it possible for you to release your pre-proceed data? I believe it is important for the community to align their experiment results with your baseline.

**Comment by ChenFengYe** [comment]
> I encounter similar problem with @ChenFengYe. Although the difference in Mean and Std is relatively small, it causes a difference in all the metrics, including GT. Is it possible for you to release your pre-proceed data? I believe it is important for the community to align their experiment results with your baseline.

I guess Guo wants to release his pre-proceed data, but the license of AMASS dataset does not allow it.

**Comment by EricGuo5513** [comment]
> > I encounter similar problem with @ChenFengYe. Although the difference in Mean and Std is relatively small, it causes a difference in all the metrics, including GT. Is it possible for you to release your pre-proceed data? I believe it is important for the community to align their experiment results with your baseline.
> 
> I guess Guo wants to release his pre-proceed data, but the license of AMASS dataset does not allow it.

Thanks @ChenFengYe! Yes, we need to follow the distribution policy of amass dataset. Therefore we can not release the pre-processed data publicly. However, please feel free to contact cguo2@ualberta.ca if you have any questions.
