### ISSUE TITLE
Where the external dictionary of language words was defined ?

### ISSUE THREAD

**Issue by rd20karim** [EricGuo5513/HumanML3D#30]
Hello, In the paper it was mentioned that an external dictionary was manually constructed to collect motion-related
words and categorize them into four types: direction, body part, object and action

**I can't find where it was defined in this project code ?**

**Comment by EricGuo5513** [comment]
Hi, it is in another project. See https://github.com/EricGuo5513/text-to-motion/blob/8640570682a0d0278b028e9525f385ee61f25ba9/utils/word_vectorizer.py#L46.

**Comment by rd20karim** [comment]
Thank you for providing the direct link. I see that five categories were defined, it appears that there are two different datasets - HumanML3D (22 joints) and The generated KiT version (21 joints). I'm interested in knowing if this dictionary categorizes all of the vocabulary found within these datasets.

**Comment by EricGuo5513** [comment]
Yes, for both dataset we use the same dictionary.
