### ISSUE TITLE
animation ipython file Error: index 2 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by katsully** [EricGuo5513/HumanML3D#31]
Everything was fine, the double checks were all fairly close to 0 (for example 0.0047665355)
But the last code block of code in animation.ipynb gave me this error.

<img width="755" alt="Capture" src="https://user-images.githubusercontent.com/4348793/216639690-69a34541-7ab6-4113-b973-7224f2883d07.PNG">

**Comment by EricGuo5513** [comment]
Hi, please check if that motion has more than one frames. It seems there is
only one frame in that motion.

**Comment by MichaelaQ** [comment]
hello，I have the same problem.Could you please tell me how to solve it?

**Comment by guoti777** [comment]
to fix it, you can change this line in "animation.ipynb":
data = joints.copy().reshape(len(joints), -1, 3)
to
data = joints.copy().reshape(-1, 22, 3)
