### ISSUE TITLE
The skeleton structure and indexes of body joints used in HumanML3D

### ISSUE THREAD

**Issue by Dean-UQ** [EricGuo5513/HumanML3D#32]
Hi, 

   I notice that the paper says that motions in HumanML3D dataset follow the skeleton structure of SMPL with 22 joints. However, the official skeleton structure of SMPL has 23 body joints. I would like to know what is the detailed skeleton structure and indexes of body joints of HumanML3D.

Many Thanks for your reply and help.

**Comment by EricGuo5513** [comment]
Hi, we do not use the hand index in SMPL. Basically, we are using the first
22 joint in SMPL. For kinematic chain, you could refer to the paramUtill.py

**Comment by Dean-UQ** [comment]
Thanks, I find it.
