### ISSUE TITLE
In inverse_kinematics_np, why root_quat = qbetween_np(forward, target) 

### ISSUE THREAD

**Issue by changhongjian** [EricGuo5513/HumanML3D#35]
I think the right code is 
` root_quat = qbetween_np(target, forward) ` which means rotate the `[0,0,1]` to the calculated vector `forward`

**Comment by EricGuo5513** [comment]
Either of them is fine as long as you could restore the motions after all.
Also in motion process, there is a step in which we make all poses facing
Z+ direction.

**Comment by changhongjian** [comment]
> 
感谢你的回复，用中文吧。
虽然我没有检查效果，但是我认为在IK中这个全局旋转求法和后面骨骼关节旋转求法是不一致的。
`rot_u_v = qbetween_np(u, v)`  比如这个就很好理解，求出的是T-pose下每个骨骼转到目标骨骼的旋转。而`root_quat = qbetween_np(forward, target) ` 的含义是当前骨骼整体转到T-pose (face Z+) 下的旋转。 这样得到的两个系数会不一致，FK时应该有问题，或者说与原始的关键点对不齐。

另外还有个地方，下面这里线速度，为什么不是用相对旋转？而且我认为不用旋转也行(就是表示速度，而不是对齐线速度的定义)。
`
# (seq_len - 1, 3)
velocity = (positions[1:, 0] - positions[:-1, 0]).copy()
#     print(r_rot.shape, velocity.shape)
velocity = qrot_np(r_rot[1:], velocity) # why not relative rotation
`

**Comment by EricGuo5513** [comment]
哈喽，FK的时候， root的rotation相对于local pose是单独处理的。这里我们表示为forward-》target的旋转，是因为我们后面需要把所有的pose都消除global rotation，面向Z+。您也可以表示为target->forward，只要你可以后面恢复原始的pose就可以。

相对旋转其实也是在局部空间中的旋转速率，不确定是否make sense。这里消除global rotation是为了解耦全局信息和局部信息。在一些SIGGRAPH的文章中有相似的操作。

**Comment by changhongjian** [comment]
感谢你回复，应该是 PFNN 这个系列的作者吧，感觉他们论文中生成的动作平移滑步等现象比较少，但是数据处理的代码似乎给的不全。
