### ISSUE TITLE
Question Dataset

### ISSUE THREAD

**Issue by StefanoBraghetto** [EricGuo5513/HumanML3D#46]
More than an issue i have some questions. would thank you if you can answer to make everyone know.

1-Amass is a database different from HumanML3D? and the job of HumanML3D is to mix them and also put labels?
2-i'm not sure if this dataset has inside the **"The kit motion-language dataset"**. Because inside of AMASS there is a dataset called KIT
![image](https://user-images.githubusercontent.com/46006663/230719645-2c666284-b062-458b-970f-45b9c57bae1a.png)

Thanks
Stefano

**Comment by EricGuo5513** [comment]
1. Yes and yes.
2. This KIT dataset is different from the kit motion language dataset.

**Comment by StefanoBraghetto** [comment]
Thank you very much!
