### ISSUE TITLE
Big errors on motion representations but small on mean and std

### ISSUE THREAD

**Issue by sukun1045** [EricGuo5513/HumanML3D#47]
Hi! I have an issue when pre-processing the data. I follow the instructions and use the jupter notebook to process. It turns out the motion representation result has large error but the mean and std seem like in a reasonable range. Do you have any idea of why I get these results? Thanks.
![image](https://user-images.githubusercontent.com/22249737/232242520-2701cc9f-edc4-436c-bb2e-9828bf3fddac.png)
![image](https://user-images.githubusercontent.com/22249737/232242571-b51c483d-b5a4-4c67-a130-ebf395577d3a.png)

**Comment by EricGuo5513** [comment]
Hi, I guess the error comes from the the last update in skeleton.py. I have recalled the update. Could you please run motion_representation.ipynb again? If the problem is solved, would appreciate if you could let me know.

**Comment by sukun1045** [comment]
Thanks for the quick reply. Now I got the following results. Seems reasonable now.
![image](https://user-images.githubusercontent.com/22249737/232245871-7d375b99-472d-48c1-8cf3-b70b4013aada.png)
![image](https://user-images.githubusercontent.com/22249737/232245885-fb88ef1d-bd40-47fc-8ba7-b9dc8f84c6c1.png)

**Comment by EricGuo5513** [comment]
That would be great.
