### ISSUE TITLE
Compare with other dataset

### ISSUE THREAD

**Issue by ChenFengYe** [EricGuo5513/HumanML3D#5]
No offense. I notice there is a similar dataset [BABEL](https://github.com/abhinanda-punnakkal/BABEL) (also mentioned in your paper). Is there any comparison or differences between the two datasets (like Tab. 1 in your paper)? I think both two works are valuable, but try to figure out their features or focus.

**Comment by EricGuo5513** [comment]
Hi, no worries. BABEL mainly focuses on action label. They have both coarse/fine-grained frame-level action labels. Our dataset mainly focuses on free-form language. And for each piece of data, we have multiple anotations.
