### ISSUE TITLE
meaning of results inside joints folder after 'raw_pose_processing.ipynb'

### ISSUE THREAD

**Issue by yh675** [EricGuo5513/HumanML3D#52]
Hello, thanks for the awesome work!

For the output of 'raw_pose_processing.ipynb' which is inside the joints folder. The numpy files have the format [number of frames, 52, 3].

I am wondering what the dimensions (52, 3) represent.

Do they represent the (x,y,z) translations of first 22 SMPL joints plus something else?

**Comment by EricGuo5513** [comment]
Hi, in Amass dataset, there are also hand joints.

**Comment by yh675** [comment]
Thanks for responding.

What I mean is, for that dimension of size 52. What does each element represent?
I know that HumanML3d uses the first 22 SMPL joints, but how is the total number of dimensions 52?

**Comment by EricGuo5513** [comment]
Hi,

Each entry of 52 is a skeleton joint. In amass, basically they have SMPL(22
joints) plus hand joints(30 joints). While for HumanML3D, we only take the
22 SMPL joints.

**Comment by yh675** [comment]
Ok I see, 
So if I have my own data in SMPL format, 
I could convert it to HumanML3D format, by leaving the last (30, 3) dimensions as zeros?

**Comment by EricGuo5513** [comment]
In the next step, we would only pick the first 22 joints.  So, you could do
the same.

**Comment by yh675** [comment]
ok thank you
