### ISSUE TITLE
Large Error on Motion_representation

### ISSUE THREAD

**Issue by layumi** [EricGuo5513/HumanML3D#56]
Dear authors, 

Thanks a lot for providing such great code. 

I meet a problem on ``motion_representation''.  Do you have any idea about it? Due to numpy? 

![image](https://user-images.githubusercontent.com/8390471/235338110-a8432d82-6ed4-49fb-9cf0-392c0716c140.png)

I am really appreciate if you could provide one joint file under ``joints'' or other material that I can verify the joints preparation in the first step.

**Comment by layumi** [comment]
Could you upload ``joints/012314.npy''? Thanks a lot.

**Comment by layumi** [comment]
I just used ``animation.ipynb'' to generate the animation. The animation seems correct, which is aligned with the text description. So maybe the joints are correct.

**Comment by layumi** [comment]
I guess it is the same problem with https://github.com/EricGuo5513/HumanML3D/issues/47

**Comment by kruzel** [comment]
I am getting similar errors about array reshape, how can I overcome this?

![image](https://github.com/EricGuo5513/HumanML3D/assets/975963/2d1fa8f6-b02a-48aa-9883-b0d38d1e3c08)

**Comment by JewelChen2019** [comment]
> I am getting similar errors about array reshape, how can I overcome this?
> 
> ![image](https://user-images.githubusercontent.com/975963/269354047-2d1fa8f6-b02a-48aa-9883-b0d38d1e3c08.png)

hello~ so how do u overcome this? (and  is there necessary to eliminate this error?
