### ISSUE TITLE
Extract SMPLH thetas from your vector

### ISSUE THREAD

**Issue by GuyTevet** [EricGuo5513/HumanML3D#6]
How can I extract SMPLH thetas (21 joints * 6d) from your 263/251 pose vector?
Thanks!

**Comment by EricGuo5513** [comment]
Hi, unfortunately you can not extract SMPLH parameters from the pose vector. But you can fit it according to the 3D positions using this https://github.com/wangsen1312/joints2smpl

**Comment by GuyTevet** [comment]
Cool thanks!
