### ISSUE TITLE
Slice in raw_pose_processing.ipynb

### ISSUE THREAD

**Issue by Mathux** [EricGuo5513/HumanML3D#7]
Hi @EricGuo5513,

First of all, thanks for your work and for releasing this dataset.

I have a question concerning the creation/conversion of this dataset. At the end of the file [raw_pose_processing.ipynb](https://github.com/EricGuo5513/HumanML3D/blob/main/raw_pose_processing.ipynb), there is this bloc of line which I don't understand:
![](https://i.gyazo.com/5d857c4db361c15b7c08973526720225.png)

I have some questions:
- Why the beginning of the sequence is trimmed? (Is it to remove T-pose/A-pose?)
- Why the "amount of trim" changes according to the data (at this point in the code, they are already downsampled to the fixed fps=20).

Thanks a lot for your help

**Comment by EricGuo5513** [comment]
Hi, yes, we trim the beginning poses to remove A-Pose/T-Pose part.

It varies for different sub-dataset because the duration of A/T-Pose part
for these dataset is also different. Here, we just have a rough
approximation.
