### ISSUE TITLE
How to generate HumanML3D data from video?

### ISSUE THREAD

**Issue by zhuangzhuang000** [EricGuo5513/HumanML3D#8]
Hello!

Thank you for sharing the dataset. May I ask how to generate data in the same format as HumanML3D from my own recorded video?

 As far as I know, we can use the VIBE method to extract smpl data from the video, but the smpl data generated by VIBE is still different from the smplh data provided by AMASS. Can you give me some advice?

**Comment by EricGuo5513** [comment]
Hi, that should not be a problem. Because the Humanact12 dataset, a part of HumanML3D, is from SMPL data. SMPLH and SMPL have the same kinematic chains except SMPLH extraly has hand pose. However, hand pose is not included in our data. So you just need to get the 3d positions of your custom data, and run the motion_representation.py.

**Comment by zhuangzhuang000** [comment]
> Hi, that should not be a problem. Because the Humanact12 dataset, a part of HumanML3D, is from SMPL data. SMPLH and SMPL have the same kinematic chains except SMPLH extraly has hand pose. However, hand pose is not included in our data. So you just need to get the 3d positions of your custom data, and run the motion_representation.py.

thanks for your help!

**Comment by lizc126** [comment]
> > Hi, that should not be a problem. Because the Humanact12 dataset, a part of HumanML3D, is from SMPL data. SMPLH and SMPL have the same kinematic chains except SMPLH extraly has hand pose. However, hand pose is not included in our data. So you just need to get the 3d positions of your custom data, and run the motion_representation.py.
> 
> thanks for your help!

Hi @zhuangzhuang000 , hv you figured out hot to convert VIBE output to HumanML3D format? I am using CLIFF and met the same issue. Thank you!

**Comment by mayank64ce** [comment]
yeah I also want to know how to convert a single VIBE pose to HumanML3D output.

**Comment by AlbertBJ** [comment]
> > Hi, that should not be a problem. Because the Humanact12 dataset, a part of HumanML3D, is from SMPL data. SMPLH and SMPL have the same kinematic chains except SMPLH extraly has hand pose. However, hand pose is not included in our data. So you just need to get the 3d positions of your custom data, and run the motion_representation.py.
> 
> thanks for your help!

i also want  to know how to convert VIBE output to HumanML3D format. Could u help me ?

**Comment by PixelPantz** [comment]
Hello everyone, has anyone found a solution for converting a video to the SMPL format?
