### ISSUE TITLE
Question regarding the 263-length pose vector in HumanML3D

### ISSUE THREAD

**Issue by Bingrong89** [EricGuo5513/HumanML3D#83]
Hello, thank you for your wonderful work. I am trying to understand the derivation for the pose vector length.
As I understand for the feature vector derived from the 22 joints SMPL model, the pose vector is 263 in length.

It is derived from below, which you posted somewhere else.

root_rot_velocity (B, seq_len, 1)
root_linear_velocity (B, seq_len,2)
root_y (B, seq_len, 1)
ric_data (B, seq_len, (joint_num - 1)*3)
rot_data (B, seq_len, (joint_num - 1)*6)
local_velocity (B, seq_len,joint_num*3)
foot contact (B, seq_len, 4)

And the SMPL joint indexing for 22 joints is as below

['pelvis',
 'left_hip',
 'right_hip',
 'spine1',
 'left_knee',
 'right_knee',
 'spine2',
 'left_ankle',
 'right_ankle',
 'spine3',
 'left_foot',
 'right_foot',
 'neck',
 'left_collar',
 'right_collar',
 'head',
 'left_shoulder',
 'right_shoulder',
 'left_elbow',
 'right_elbow',
 'left_wrist',
 'right_wrist']

I am trying to understand why at ric_data and rot_data, there is a joint_num-1, as the published paper did not include this -1, under 5.Experiments:Pose Representation.
I am not sure why the right_wrist is omitted from position and rotation data. Could you kindly explain, or correct me if I am wrong? Thank you.

**Comment by EricGuo5513** [comment]
Hi, because we have include root information in the first three components:
root_rot_velocity (B, seq_len, 1)
root_linear_velocity (B, seq_len,2)
root_y (B, seq_len, 1)

Therefore, for ric_data and rot_data, we do not involve root joint any more.

**Comment by Bingrong89** [comment]
Understood, thank you!
Closing issue.
