### ISSUE TITLE
KIT-ML dataset construction

### ISSUE THREAD

**Issue by luizacbcampos** [EricGuo5513/HumanML3D#92]
Hi,
I'd like to construct the KIT-ML dataset on my computer, but I have a few questions. Where did you download the data? Was it from the KIT website or AMASS? And where did you get the text data for KIT?
Thanks

**Comment by EricGuo5513** [comment]
Hi,

KIT dataset comes from
https://motion-annotation.humanoids.kit.edu/dataset/.

**Comment by Vincent-2017** [comment]
@EricGuo5513 hi，I find the root rotation and position, and other joint rotatation values in the xxx_mmm.xml，but not find the joint offset in the file, where can i get the joint offset for fk?
